CREATE TABLE IF NOT EXISTS percolator(
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       hash bytea NOT NULL,
       owner text,
       created timestamptz NOT NULL,
       current_id bigint NOT NULL,
       query jsonb NOT NULL,
       CONSTRAINT pcl_unique_hash UNIQUE NULLS NOT DISTINCT(hash, owner)
);

-- The event table is unlogged, cheaper, but not persistent:
-- https://www.crunchydata.com/blog/postgresl-unlogged-tables
CREATE UNLOGGED TABLE IF NOT EXISTS percolator_event(
       percolator bigint NOT NULL,
       id bigint NOT NULL,
       created timestamptz NOT NULL,
       payload jsonb NOT NULL,
       PRIMARY KEY(percolator, id)
);

CREATE INDEX percolator_event_created
          ON percolator_event(created);

CREATE TABLE IF NOT EXISTS subscription(
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       percolator bigint NOT NULL,
       client text NOT NULL,
       hash bytea NOT NULL,
       touched timestamptz NOT NULL,
       spec jsonb NOT NULL,
       CONSTRAINT sub_unique_hash UNIQUE NULLS NOT DISTINCT(percolator, client, hash),
       FOREIGN KEY(percolator) REFERENCES percolator(id)
               ON DELETE CASCADE
);

---- create above / drop below ----

DROP TABLE IF EXISTS subscription;
DROP TABLE IF EXISTS percolator_event;
DROP TABLE IF EXISTS percolator;
