// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppState struct {
	Name string
	Data AppStateData
}

type Cluster struct {
	Name    string
	Url     string
	Auth    []byte
	Created pgtype.Timestamptz
}

type DocumentIndex struct {
	Name         string
	SetName      string
	ContentType  string
	Mappings     []byte
	FeatureFlags []string
}

type IndexSet struct {
	Name     string
	Position int64
	Cluster  pgtype.Text
	Active   bool
	Enabled  bool
	Deleted  bool
	Modified pgtype.Timestamptz
	CaughtUp bool
}

type IndexingOverride struct {
	ContentType string
	Field       string
	Mapping     []byte
}

type JobLock struct {
	Name      string
	Holder    string
	Touched   pgtype.Timestamptz
	Iteration int64
}

type Percolator struct {
	ID      int64
	Hash    []byte
	Owner   pgtype.Text
	Created pgtype.Timestamptz
	DocType string
	Query   map[string]any
}

type PercolatorEvent struct {
	ID         int64
	Document   uuid.UUID
	Percolator int64
	Created    pgtype.Timestamptz
}

type PercolatorEventPayload struct {
	ID      int64
	Created pgtype.Timestamptz
	Data    PercolatorDocument
}

type SchemaVersion struct {
	Version int32
}

type Subscription struct {
	ID         int64
	Percolator int64
	Client     string
	Hash       []byte
	Touched    pgtype.Timestamptz
	Spec       SubscriptionSpec
}
