// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cluster struct {
	Name    string
	Url     string
	Auth    []byte
	Created pgtype.Timestamptz
}

type DocumentIndex struct {
	Name         string
	SetName      string
	ContentType  string
	Mappings     []byte
	FeatureFlags []string
}

type IndexSet struct {
	Name     string
	Position int64
	Cluster  pgtype.Text
	Active   bool
	Enabled  bool
	Deleted  bool
	Modified pgtype.Timestamptz
}

type IndexingOverride struct {
	ContentType string
	Field       string
	Mapping     []byte
}

type JobLock struct {
	Name      string
	Holder    string
	Touched   pgtype.Timestamptz
	Iteration int64
}

type SchemaVersion struct {
	Version int32
}
