// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DocumentIndex struct {
	Name        string
	SetName     string
	ContentType string
	Mappings    []byte
}

type IndexSet struct {
	Name     string
	Position int64
}

type IndexingOverride struct {
	ContentType string
	Field       string
	Mapping     []byte
}

type JobLock struct {
	Name      string
	Holder    string
	Touched   pgtype.Timestamptz
	Iteration int64
}

type SchemaVersion struct {
	Version int32
}
