--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1 (Debian 16.1-1.pgdg120+1)
-- Dumped by pg_dump version 16.1 (Debian 16.1-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_state (
    name text NOT NULL,
    data jsonb NOT NULL
);


--
-- Name: cluster; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cluster (
    name text NOT NULL,
    url text NOT NULL,
    auth jsonb NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: document_index; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_index (
    name text NOT NULL,
    set_name text NOT NULL,
    content_type text NOT NULL,
    mappings jsonb NOT NULL,
    feature_flags text[]
);


--
-- Name: index_set; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.index_set (
    name text NOT NULL,
    "position" bigint NOT NULL,
    cluster text,
    active boolean DEFAULT false NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    caught_up boolean DEFAULT false NOT NULL
);


--
-- Name: indexing_override; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.indexing_override (
    content_type text NOT NULL,
    field text NOT NULL,
    mapping jsonb NOT NULL
);


--
-- Name: job_lock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_lock (
    name text NOT NULL,
    holder text NOT NULL,
    touched timestamp with time zone NOT NULL,
    iteration bigint NOT NULL
);


--
-- Name: percolator; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.percolator (
    id bigint NOT NULL,
    hash bytea NOT NULL,
    owner text,
    created timestamp with time zone NOT NULL,
    doc_type text NOT NULL,
    query jsonb NOT NULL,
    deleted boolean DEFAULT false NOT NULL
);


--
-- Name: percolator_document_index; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.percolator_document_index (
    percolator bigint NOT NULL,
    index text NOT NULL
);


--
-- Name: percolator_event; Type: TABLE; Schema: public; Owner: -
--

CREATE UNLOGGED TABLE public.percolator_event (
    id bigint NOT NULL,
    document uuid NOT NULL,
    percolator bigint NOT NULL,
    matched boolean NOT NULL,
    created timestamp with time zone NOT NULL
);


--
-- Name: percolator_event_payload; Type: TABLE; Schema: public; Owner: -
--

CREATE UNLOGGED TABLE public.percolator_event_payload (
    id bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    data jsonb NOT NULL
);


--
-- Name: percolator_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.percolator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.percolator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_version (
    version integer NOT NULL
);


--
-- Name: subscription; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscription (
    id bigint NOT NULL,
    percolator bigint NOT NULL,
    client text NOT NULL,
    hash bytea NOT NULL,
    touched timestamp with time zone NOT NULL,
    spec jsonb NOT NULL
);


--
-- Name: subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_state app_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_state
    ADD CONSTRAINT app_state_pkey PRIMARY KEY (name);


--
-- Name: cluster cluster_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cluster
    ADD CONSTRAINT cluster_pkey PRIMARY KEY (name);


--
-- Name: document_index document_index_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_index
    ADD CONSTRAINT document_index_pkey PRIMARY KEY (name);


--
-- Name: index_set index_set_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.index_set
    ADD CONSTRAINT index_set_pkey PRIMARY KEY (name);


--
-- Name: indexing_override indexing_override_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.indexing_override
    ADD CONSTRAINT indexing_override_pkey PRIMARY KEY (content_type, field);


--
-- Name: job_lock job_lock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_lock
    ADD CONSTRAINT job_lock_pkey PRIMARY KEY (name);


--
-- Name: percolator pcl_unique_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.percolator
    ADD CONSTRAINT pcl_unique_hash UNIQUE NULLS NOT DISTINCT (hash, owner);


--
-- Name: percolator_document_index percolator_document_index_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.percolator_document_index
    ADD CONSTRAINT percolator_document_index_pkey PRIMARY KEY (percolator, index);


--
-- Name: percolator_event_payload percolator_event_payload_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.percolator_event_payload
    ADD CONSTRAINT percolator_event_payload_pkey PRIMARY KEY (id);


--
-- Name: percolator_event percolator_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.percolator_event
    ADD CONSTRAINT percolator_event_pkey PRIMARY KEY (id, percolator);


--
-- Name: percolator percolator_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.percolator
    ADD CONSTRAINT percolator_pkey PRIMARY KEY (id);


--
-- Name: subscription sub_unique_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT sub_unique_hash UNIQUE NULLS NOT DISTINCT (percolator, client, hash);


--
-- Name: subscription subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT subscription_pkey PRIMARY KEY (id);


--
-- Name: document_index_content_type_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_index_content_type_idx ON public.document_index USING btree (content_type);


--
-- Name: percolator_event_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX percolator_event_created ON public.percolator_event USING btree (created);


--
-- Name: percolator_event_payload_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX percolator_event_payload_created ON public.percolator_event_payload USING btree (created);


--
-- Name: unique_single_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unique_single_active ON public.index_set USING btree (active) WHERE (active = true);


--
-- Name: document_index document_index_set_name_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_index
    ADD CONSTRAINT document_index_set_name_fkey FOREIGN KEY (set_name) REFERENCES public.index_set(name) ON DELETE CASCADE;


--
-- Name: index_set fk_set_cluster; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.index_set
    ADD CONSTRAINT fk_set_cluster FOREIGN KEY (cluster) REFERENCES public.cluster(name) ON DELETE CASCADE;


--
-- Name: percolator_document_index percolator_document_index_percolator_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.percolator_document_index
    ADD CONSTRAINT percolator_document_index_percolator_fkey FOREIGN KEY (percolator) REFERENCES public.percolator(id) ON DELETE CASCADE;


--
-- Name: subscription subscription_percolator_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT subscription_percolator_fkey FOREIGN KEY (percolator) REFERENCES public.percolator(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

