name: Build

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Create Docker image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: registry.a.tt.se
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: registry.a.tt.se/docker/tonistiigi/binfmt:qemu-v7.0.0

      - name: Create build context
        run: docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders

      - name: Set up TT environment
        run: |
          version_ref=$(git describe --tags HEAD 2>&- || \
            echo v0.0.0-$(git rev-list HEAD --count)-$(git rev-parse --short HEAD))
          (
          echo version_ref=${version_ref}
          echo docker_repo=registry.a.tt.se/${{ github.repository }}
          echo docker_image=registry.a.tt.se/${{ github.repository }}:${version_ref}
          ) >> $GITHUB_ENV

      - name: Build and push release image
        uses: docker/build-push-action@v3
        with:
          context: .
          # Specify the build_platforms variable in the GitHub repo
          platforms: ${{ vars.BUILD_PLATFORMS }}
          push: true
          build-args: |
            COMMAND=index
          tags: ${{ env.docker_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
